configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/test-arockiyaagithub%2Faro-test-sdk-636b118dcb9cf2e9b84d2a535afafc18eaec223cead1786a28322e261fb0aa5f.yml
